---
sidebar: sidebar 
permalink: concept_api_understanding_scripts.html 
keywords: rest api, deploy rest api, rest, python, python scripts, understanding 
summary: Los scripts de ejemplo de Python permiten realizar diversas tareas. Es recomendable comprenderlos antes de usarlos en una instancia de Deploy activa. 
---
= Comprenda los scripts de Python para ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los scripts de ejemplo de Python permiten realizar diversas tareas. Es recomendable comprenderlos antes de usarlos en una instancia de Deploy activa.



== Características de diseño comunes

Los scripts han sido diseñados con las siguientes características comunes:

* Ejecutar desde la interfaz de línea de comandos en un equipo cliente. Puede ejecutar los scripts de Python desde cualquier equipo cliente correctamente configurado. Consulte "Antes de comenzar" para obtener más información.
* Aceptar parámetros de entrada CLI Cada script se controla en la CLI a través de parámetros de entrada.
* Leer archivo de entrada. Cada script lee un archivo de entrada según su propósito. Al crear o eliminar un clúster, debe proporcionar un archivo de configuración JSON. Al agregar una licencia de nodo, debe proporcionar un archivo de licencia válido.
* Usar un módulo de soporte común. El módulo de soporte común _deploy_requests.py_ contiene una sola clase. Se importa y utiliza en cada script.




== Crear un clúster

Puede crear un clúster de ONTAP Select con el script cluster.py. Según los parámetros de la CLI y el contenido del archivo de entrada JSON, puede adaptar el script a su entorno de implementación de la siguiente manera:

* Hipervisor: Puede implementar en ESXI o KVM (según la versión de implementación). Al implementar en ESXi, el hipervisor puede ser administrado por vCenter o puede ser un host independiente.
* Tamaño del clúster Puede implementar un clúster de un solo nodo o de varios nodos.
* Licencia de evaluación o producción Puede implementar un clúster con una licencia de evaluación o comprada para producción.


Los parámetros de entrada CLI para el script incluyen:

* Nombre de host o dirección IP del servidor de implementación
* Contraseña para la cuenta de usuario administrador
* Nombre del archivo de configuración JSON
* Bandera verbosa para la salida del mensaje




== Agregar una licencia de nodo

Si decide implementar un clúster de producción, debe agregar una licencia para cada nodo mediante el script _add_license.py_. Puede agregar la licencia antes o después de implementar el clúster.

Los parámetros de entrada CLI para el script incluyen:

* Nombre de host o dirección IP del servidor de implementación
* Contraseña para la cuenta de usuario administrador
* Nombre del archivo de licencia
* Nombre de usuario de ONTAP con privilegios para agregar la licencia
* Contraseña para el usuario de ONTAP




== Eliminar un clúster

Puede eliminar un clúster de ONTAP Select existente mediante el script _delete_cluster.py_.

Los parámetros de entrada CLI para el script incluyen:

* Nombre de host o dirección IP del servidor de implementación
* Contraseña para la cuenta de usuario administrador
* Nombre del archivo de configuración JSON

