---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: Después de implementar un clúster ONTAP Select , puede actualizar la imagen de ONTAP de cada nodo según sea necesario utilizando el procedimiento de actualización de software de ONTAP estándar. 
---
= Actualizar los nodos ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Después de implementar un clúster ONTAP Select , puede actualizar la imagen de ONTAP en cada nodo del clúster según sea necesario.


CAUTION: No se puede usar la utilidad de administración de implementación para actualizar nodos de ONTAP Select existentes. La utilidad de implementación solo se puede usar para crear nuevos clústeres de ONTAP Select .



== Procedimiento general

En un nivel alto, debe utilizar los siguientes pasos para actualizar un nodo ONTAP Select existente.

. Vaya a la página de descargas en el sitio de soporte de NetApp .
+
https://mysupport.netapp.com/site/downloads["Descargas de soporte de NetApp"^]

. Haga clic en *Actualizar nodo ONTAP Select *.
. Seleccione y descargue la imagen de actualización adecuada respondiendo a todas las indicaciones según sea necesario.
+
Revise las Notas de la versión para obtener información adicional y los procedimientos necesarios antes de actualizar un nodo ONTAP Select .

. Actualice el nodo ONTAP Select mediante los procedimientos estándar de actualización de ONTAP con el archivo de actualización de ONTAP Select . Para obtener información sobre las rutas de actualización compatibles, consulte lalink:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html["Rutas de actualización de ONTAP compatibles"^] .




== Revertir un nodo de ONTAP Select

No es posible revertir un nodo ONTAP Select a una versión anterior a aquella en la que fue instalado originalmente. Por ejemplo:

ONTAP Select 9.16.1 se instala inicialmente:: Puede actualizar el nodo a la versión 9.17.1 y luego volver a la versión 9.16.1 si es necesario.
ONTAP Select 9.17.1 se instala inicialmente:: No es posible revertir el proceso porque no había ninguna versión anterior instalada.




== Utilice el controlador de red VMXNET3

VMXNET3 es el controlador de red predeterminado incluido en las nuevas implementaciones de clústeres en VMware ESXi. Si actualiza un nodo de ONTAP Select existente con ONTAP Select 9.4 o una versión anterior, el controlador de red no se actualiza automáticamente. Debe actualizar manualmente a VMXNET3. Para obtener ayuda con la actualización, póngase en contacto con el soporte de NetApp .

.Información relacionada
link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["Descripción general de la actualización de ONTAP"^]
