---
sidebar: sidebar 
permalink: concept_usecase_overview.html 
keywords: ontap select, business use case overview, deployment, storage, development and testing 
summary: ONTAP Select es adecuado para varios tipos diferentes de aplicaciones gracias a la flexibilidad inherente que proporciona la virtualización del hipervisor. 
---
= ONTAP Select necesidades comerciales y escenarios de uso
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select es adecuado para varios tipos diferentes de aplicaciones gracias a la flexibilidad inherente que proporciona la virtualización del hipervisor.



== Despliegue

Desde un nivel alto, puede implementar ONTAP Select de dos maneras diferentes con respecto a la carga de trabajo en los servidores host del hipervisor.



=== Implementación dedicada

Con el modelo de implementación dedicado, una sola instancia de ONTAP Select se ejecuta en el servidor host. Ningún otro procesamiento significativo se ejecuta en el mismo host de hipervisor.



=== Despliegue en ubicación conjunta

Con el modelo de implementación coubicada, ONTAP Select comparte el host con otras cargas de trabajo. En concreto, existen máquinas virtuales adicionales, cada una de las cuales suele ejecutar aplicaciones computacionales. Estas cargas de trabajo computacionales son locales en el clúster de ONTAP Select . Este modelo admite requisitos de aplicación e implementación especializados. Al igual que con el modelo de implementación dedicado, cada máquina virtual de ONTAP Select debe ejecutarse en un host de hipervisor independiente y dedicado.



== Almacenamiento

ONTAP Select se puede utilizar como almacenamiento principal o secundario, según las necesidades de su negocio.



=== Almacenamiento primario

En algunos casos, puede optar por implementar ONTAP Select como su plataforma de almacenamiento principal. Este tipo de implementación varía y depende de las características de la carga de trabajo de las aplicaciones, así como de sus objetivos comerciales.



=== Recuperación ante desastres y almacenamiento secundario

Puede usar ONTAP Select para implementar almacenamiento adicional que complemente sus capacidades de almacenamiento principal. Este almacenamiento adicional puede utilizarse para respaldar los esfuerzos de recuperación ante desastres y los planes de respaldo de datos de su organización.



== Desarrollo y pruebas

Al implementar diversas aplicaciones en su organización, puede usar ONTAP Select como parte integral del proceso general de desarrollo y pruebas de aplicaciones. Por ejemplo, podría necesitar almacenamiento temporal para guardar datos de entrada o salida de pruebas. La duración de este tipo de implementaciones puede variar según las características y requisitos de la aplicación.
