---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: Primero, familiarícese con los conceptos generales de red aplicables al entorno ONTAP Select . Luego, explore las características y opciones específicas disponibles con los clústeres de un solo nodo y de varios nodos. 
---
= Conceptos y características de la red ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Primero, familiarícese con los conceptos generales de red aplicables al entorno ONTAP Select . Luego, explore las características y opciones específicas disponibles con los clústeres de un solo nodo y de varios nodos.



== Redes físicas

La red física admite la implementación de un clúster ONTAP Select principalmente al proporcionar la infraestructura de conmutación de capa 2 subyacente. La configuración de la red física incluye tanto el host del hipervisor como el entorno de red conmutada más amplio.



=== Opciones de NIC del host

Cada host de hipervisor ONTAP Select debe configurarse con dos o cuatro puertos físicos. La configuración exacta que elija dependerá de varios factores, entre ellos:

* Si el clúster contiene uno o varios hosts ONTAP Select
* ¿Qué sistema operativo de hipervisor se utiliza?
* Cómo se configura el conmutador virtual
* Si se utiliza LACP con los enlaces o no




=== Configuración del conmutador físico

Debe asegurarse de que la configuración de los conmutadores físicos sea compatible con la implementación de ONTAP Select . Los conmutadores físicos están integrados con los conmutadores virtuales basados en hipervisor. La configuración exacta que elija depende de varios factores. Las principales consideraciones incluyen las siguientes:

* ¿Cómo mantendrá la separación entre las redes internas y externas?
* ¿Mantendrá una separación entre las redes de datos y de gestión?
* ¿Cómo se configurarán las VLAN de capa dos?




== Redes lógicas

ONTAP Select utiliza dos redes lógicas diferentes, separando el tráfico según su tipo. En concreto, el tráfico puede fluir entre los hosts dentro del clúster, así como hacia los clientes de almacenamiento y otras máquinas fuera del clúster. Los conmutadores virtuales administrados por los hipervisores contribuyen al soporte de la red lógica.



=== Red interna

En una implementación de clúster multinodo, los nodos individuales de ONTAP Select se comunican mediante una red interna aislada. Esta red no está expuesta ni disponible fuera de los nodos del clúster de ONTAP Select .


NOTE: La red interna solo está presente con un clúster de varios nodos.

La red interna tiene las siguientes características:

* Se utiliza para procesar el tráfico intra-clúster de ONTAP , que incluye:
+
** Grupo
** Interconexión de alta disponibilidad (HA-IC)
** Espejo de sincronización RAID (RSM)


* Red de capa dos única basada en una VLAN
* Las direcciones IP estáticas son asignadas por ONTAP Select:
+
** Sólo IPv4
** DHCP no utilizado
** Dirección de enlace local


* El tamaño de MTU es de 9000 bytes de forma predeterminada y se puede ajustar dentro del rango de 7500 a 9000 (inclusive).




=== Red externa

La red externa procesa el tráfico entre los nodos de un clúster de ONTAP Select y los clientes de almacenamiento externo, así como las demás máquinas. La red externa forma parte de cada implementación de clúster y tiene las siguientes características:

* Se utiliza para procesar el tráfico de ONTAP , incluido:
+
** Datos (NFS, CIFS, iSCSI)
** Gestión (clúster y nodo; opcionalmente SVM)
** Intercluster (opcional)


* Admite VLAN opcionalmente:
+
** Grupo de puertos de datos
** Grupo de gestión portuaria


* Direcciones IP que se asignan según las opciones de configuración del administrador:
+
** IPv4 o IPv6


* El tamaño de MTU es 1500 bytes por defecto (se puede ajustar)


La red externa está presente con clústeres de todos los tamaños.



== Entorno de red de máquinas virtuales

El host del hipervisor proporciona varias funciones de red.

ONTAP Select se basa en las siguientes capacidades expuestas a través de la máquina virtual:

Puertos de máquinas virtuales:: Hay varios puertos disponibles para ONTAP Select. Su asignación y uso se basan en diversos factores, incluido el tamaño del clúster.
Conmutador virtual:: El software del conmutador virtual dentro del entorno de hipervisor, ya sea vSwitch (VMware) u Open vSwitch (KVM), conecta los puertos expuestos por la máquina virtual con los puertos NIC Ethernet físicos. Debe configurar un vSwitch para cada host de ONTAP Select , según corresponda a su entorno.

