---
sidebar: sidebar 
permalink: concept_ots_deploy.html 
keywords: ontap select deploy, deploy administration utility, deploy utility, functionality, accessing 
summary: ONTAP Select Deploy es la utilidad de administración que se utiliza para implementar y administrar clústeres de ONTAP Select . 
---
= Implementación de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy es la utilidad de administración que se utiliza para implementar y administrar clústeres de ONTAP Select . Deploy se entrega como una máquina virtual Linux que debe instalarse antes de crear un clúster de ONTAP Select .



== Funcionalidad principal

La utilidad de administración Deploy realiza las siguientes funciones principales:

* Registre los detalles de cada host de hipervisor donde se implementa ONTAP Select
* Configurar los hosts e instalar las licencias necesarias
* Implementar y administrar los clústeres de ONTAP Select
* Mantener un inventario de clústeres y hosts de ONTAP Select
* Recopilar y enviar datos de AutoSupport a NetApp
* Mantener un conjunto interno de imágenes de nodos de ONTAP Select
* Admite formatos y protocolos de comandos específicos del hipervisor




== Formas de acceder a la utilidad de implementación

Tiene varias opciones disponibles para acceder a la utilidad de administración de Deploy. Todas las interfaces externas son funcionalmente equivalentes. Debe seleccionar la opción de acceso que mejor se adapte a sus objetivos y requisitos de implementación. En todos los casos, debe iniciar sesión con la cuenta de administrador y una contraseña válida.



=== Interfaz gráfica de usuario web

Puede acceder a la utilidad de implementación mediante un navegador web moderno. La interfaz de usuario web proporciona una interfaz intuitiva y fácil de usar, y en la mayoría de los casos será su interfaz principal cuando utilice la utilidad.



=== Interfaz de línea de comandos

El shell de administración dispone de una interfaz de línea de comandos basada en texto. Puede acceder al shell de administración CLI de las siguientes maneras:

* Shell seguro (SSH)
* Consola de máquina virtual


Normalmente se utiliza la consola de la máquina virtual durante el proceso de instalación y configuración inicial. Sin embargo, en la mayoría de los casos, SSH ofrece una opción más flexible y práctica.



=== API de servicios web REST

La API de servicios web REST expuesta a clientes externos ofrece otra opción al conectarse a la utilidad de implementación. Puede acceder a la API mediante cualquier lenguaje de programación o herramienta compatible con servicios web REST. Las opciones más comunes incluyen:

* Pitón
* Java
* Rizo


El uso de un lenguaje de programación o scripting brinda la oportunidad de automatizar la implementación y la administración de los clústeres de ONTAP Select .



=== Página web de documentación en línea de ONTAP Select

Mostrar la página web de la documentación en línea en la utilidad de implementación es una forma alternativa de acceder a la API de servicios web REST. Sin embargo, en lugar de usar un lenguaje de programación, se accede a la API de administración a través de la página mediante un navegador. Se proporcionan las siguientes funciones:

* Una descripción detallada de cada llamada en la API de servicios web REST
* La capacidad de emitir manualmente cualquiera de las llamadas API


Puede acceder a la página de documentación en línea utilizando la IP o el nombre de dominio de la máquina virtual Deploy. Para visualizar la página, introduzca en su navegador una URL con el siguiente formato (sustituyendo la dirección IP o el nombre de dominio correspondiente a su instancia de máquina virtual de Deploy): `\http://<ip_address>/api/ui`
