---
sidebar: sidebar 
permalink: concept_api_operation.html 
keywords: rest api, deploy rest api, rest, operation, basic operation 
summary: Si bien REST establece un conjunto común de tecnologías y mejores prácticas, los detalles de cada API pueden variar según las opciones de diseño. Debe conocer los detalles y las características operativas de la API ONTAP Select Deploy antes de usarla. 
---
= Características operativas básicas de la API de implementación de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si bien REST establece un conjunto común de tecnologías y mejores prácticas, los detalles de cada API pueden variar según las opciones de diseño. Debe conocer los detalles y las características operativas de la API ONTAP Select Deploy antes de usarla.



== Host de hipervisor versus ONTAP Select

Un host de hipervisor es la plataforma de hardware principal que aloja una máquina virtual ONTAP Select . Cuando una máquina virtual de ONTAP Select se implementa y está activa en un host de hipervisor, se considera un nodo de ONTAP Select. Con la versión 3 de la API REST de Deploy, los objetos de host y nodo son independientes. Esto permite una relación de uno a muchos, donde uno o más nodos de ONTAP Select pueden ejecutarse en el mismo host de hipervisor.



== Identificadores de objetos

A cada instancia u objeto de recurso se le asigna un identificador único al crearse. Estos identificadores son únicos globalmente dentro de una instancia específica de ONTAP Select Deploy. Tras realizar una llamada a la API que crea una nueva instancia de objeto, el valor de id asociado se devuelve al llamador en el `location` encabezado de la respuesta HTTP. Puede extraer el identificador y usarlo en llamadas posteriores al hacer referencia a la instancia del recurso.


NOTE: El contenido y la estructura interna de los identificadores de objeto pueden cambiar en cualquier momento. Solo debe usar los identificadores en las llamadas a la API correspondientes según sea necesario al referirse a los objetos asociados.



== Identificadores de solicitud

A cada solicitud de API exitosa se le asigna un identificador único. El identificador se devuelve en el `request-id` encabezado de la respuesta HTTP asociada. Puede usar un identificador de solicitud para referirse colectivamente a las actividades de una única transacción de solicitud-respuesta de API específica. Por ejemplo, puede recuperar todos los mensajes de evento de una transacción según el ID de la solicitud.



== Llamadas sincrónicas y asincrónicas

Hay dos formas principales en que un servidor ejecuta una solicitud HTTP recibida de un cliente:

* Sincrónico El servidor ejecuta la solicitud inmediatamente y responde con un código de estado de 200, 201 o 204.
* Asíncrono: El servidor acepta la solicitud y responde con un código de estado 202. Esto indica que el servidor aceptó la solicitud del cliente e inició una tarea en segundo plano para completarla. El éxito o el fracaso final no está disponible de inmediato y debe determinarse mediante llamadas API adicionales.




== Confirmar la finalización de un trabajo de larga duración

Generalmente, cualquier operación que tarde mucho tiempo en completarse se procesa asincrónicamente mediante una tarea en segundo plano en el servidor. Con la API REST de Deploy, cada tarea en segundo plano está anclada por un objeto Job que la rastrea y proporciona información, como su estado actual. Un objeto Job, con su identificador único, se devuelve en la respuesta HTTP tras crear una tarea en segundo plano.

Puede consultar directamente el objeto "Job" para determinar si la llamada a la API asociada se realizó correctamente o no. Consulte "Procesamiento asíncrono con el objeto "Job"" para obtener más información.

Además de utilizar el objeto Trabajo, existen otras formas de determinar el éxito o el fracaso de una solicitud, entre ellas:

* Mensajes de evento: Puede recuperar todos los mensajes de evento asociados a una llamada API específica utilizando el ID de solicitud devuelto con la respuesta original. Los mensajes de evento suelen indicar si la operación fue correcta o no, y también pueden ser útiles al depurar una condición de error.
* Estado o estado del recurso Varios de los recursos mantienen un valor de estado o estado que puede consultar para determinar indirectamente el éxito o el fracaso de una solicitud.




== Seguridad

La API de implementación utiliza las siguientes tecnologías de seguridad:

* Seguridad de la capa de transporte: Todo el tráfico enviado a través de la red entre el servidor de implementación y el cliente se cifra mediante TLS. No se admite el uso del protocolo HTTP en un canal sin cifrar. Se admite la versión 1.2 de TLS.
* Autenticación HTTP. La autenticación básica se utiliza para cada transacción de la API. Se añade a cada solicitud un encabezado HTTP que incluye el nombre de usuario y la contraseña en una cadena base64.

