---
sidebar: sidebar 
permalink: concept_lic_evaluation.html 
keywords: license, licensing, evaluation, upgrade license 
summary: Puede usar una licencia de evaluación si desea evaluar ONTAP Select antes de decidirse a comprarlo. La licencia de evaluación se incluye con la utilidad de administración de ONTAP Select Deploy y se aplica automáticamente a cada nodo de ONTAP Select como parte de una implementación de evaluación. 
---
= Licencias de evaluación para implementaciones de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede implementar ONTAP Select con una licencia de evaluación o una licencia adquirida. La licencia que elija debe aplicarse a cada nodo del clúster de ONTAP Select y, por lo tanto, a todo el clúster. Puede usar una licencia de evaluación si desea evaluar ONTAP Select antes de decidirse a comprarlo. La licencia de evaluación se incluye con la utilidad de administración de ONTAP Select Deploy y se aplica automáticamente a cada nodo de ONTAP Select como parte de una implementación de evaluación.

[NOTE]
====
Para descargar la utilidad de administración ONTAP Select Deploy, necesita lo siguiente:

* Una cuenta registrada en el sitio de soporte de NetApp . Si no tienes una cuenta, consulta https://mysupport.netapp.com/site/user/registration["Registro de usuario"^] .
* A https://mysupport.netapp.com/site/downloads/evaluation/ontap-select["aceptar el acuerdo de licencia de usuario final"^] para una implementación de ONTAP Select con una licencia de evaluación.


====
Hay varias consideraciones a tener en cuenta al implementar y dar soporte a un clúster de evaluación:

* Solo puede usar el clúster con fines de evaluación. No debe usar un clúster con una licencia de evaluación en un entorno de producción.
* Debe utilizar la utilidad de administración ONTAP Select Deploy de la siguiente manera al configurar cada host:
+
** No proporcione un número de serie
** Configurar para utilizar una licencia de evaluación






== Características de la licencia

La licencia de evaluación de ONTAP Select tiene las siguientes características:

* No se requiere una licencia de producción con capacidad de almacenamiento
* El número de serie del nodo tiene veinte dígitos y lo genera automáticamente ONTAP Select Deploy
+
(no lo adquieres directamente de NetApp)

* El período de evaluación previsto por la licencia puede ser de hasta 90 días.
* El almacenamiento máximo asignado por cada nodo es el mismo que una licencia de producción




== Actualizar a una licencia de producción

Puede actualizar un clúster de evaluación de ONTAP Select para usar una licencia de producción. Tenga en cuenta las siguientes restricciones:

* Debe utilizar la utilidad de administración Deploy para realizar la actualización de la licencia
* Puede utilizar una licencia de nivel de capacidad, sin embargo, no se admiten las licencias de grupos de capacidad.
* Cada nodo debe tener suficiente almacenamiento asignado para soportar el mínimo requerido para una licencia de producción, según el tamaño del clúster.


Verlink:task_adm_licenses.html["Convertir una licencia de evaluación en una licencia de producción"] Para más información.

.Información relacionada
* link:concept_lic_production.html["Obtenga información sobre las licencias para implementaciones de producción"]
* link:deploy-evaluation-ontap-select-ovf-template.html["Implementar una instancia de evaluación de 90 días de un clúster ONTAP Select"]

