---
sidebar: sidebar 
permalink: concept_api_before_workflows.html 
keywords: rest api, deploy rest api, rest, workflows, before you begin 
summary: Debe prepararse para revisar y utilizar los procesos de flujo de trabajo. 
---
= Antes de utilizar los flujos de trabajo de la API de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debe prepararse para revisar y utilizar los procesos de flujo de trabajo.



== Comprender las llamadas API utilizadas en los flujos de trabajo

La página de documentación en línea de ONTAP Select incluye los detalles de cada llamada a la API REST. En lugar de repetir estos detalles aquí, cada llamada a la API utilizada en los ejemplos de flujo de trabajo incluye solo la información necesaria para localizarla en la página de documentación. Después de localizar una llamada a la API específica, puede revisar todos sus detalles, incluyendo los parámetros de entrada, los formatos de salida, los códigos de estado HTTP y el tipo de procesamiento de la solicitud.

La siguiente información se incluye para cada llamada API dentro de un flujo de trabajo para ayudar a localizar la llamada en la página de documentación:

* Categoría: Las llamadas a la API se organizan en la página de documentación en áreas o categorías funcionalmente relacionadas. Para encontrar una llamada a la API específica, desplácese hasta la parte inferior de la página y haga clic en la categoría de API correspondiente.
* Verbo HTTP. El verbo HTTP identifica la acción realizada en un recurso. Cada llamada a la API se ejecuta mediante un único verbo HTTP.
* Ruta: La ruta determina el recurso específico al que se aplica la acción al realizar una llamada. La cadena de ruta se añade a la URL principal para formar la URL completa que identifica el recurso.




== Construya una URL para acceder directamente a la API REST

Además de la página de documentación de ONTAP Select , también puede acceder a la API REST de Deploy directamente mediante un lenguaje de programación como Python. En este caso, la URL principal es ligeramente diferente a la URL utilizada para acceder a la página de documentación en línea. Para acceder directamente a la API, debe añadir "/api" a la cadena de dominio y puerto. Por ejemplo:
`\http://deploy.mycompany.com/api`
