---
sidebar: sidebar 
permalink: concept_terminology.html 
keywords: terminology, key concepts, concepts 
summary: A medida que comienza a explorar ONTAP Select y planificar una implementación, es útil familiarizarse primero con la terminología y los conceptos clave. 
---
= Terminología ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A medida que comienza a explorar ONTAP Select y planificar una implementación, es útil familiarizarse primero con la terminología y los conceptos clave.

Implementación de ONTAP Select:: ONTAP Select Deploy es la utilidad de administración que se utiliza para implementar clústeres de ONTAP Select . Esta utilidad se ejecuta en una máquina virtual Linux dedicada. Puede acceder a ella a través de la interfaz de usuario web, el shell de administración de la CLI y la API REST.
Máquina virtual basada en kernel:: La máquina virtual basada en kernel (KVM) es una función de virtualización del kernel de Linux que le permite actuar como plataforma de hipervisor. Es compatible con una amplia gama de sistemas operativos invitados.
Host de hipervisor versus ONTAP Select:: Un host de hipervisor es la plataforma de hardware principal que aloja una máquina virtual ONTAP Select . Cuando una máquina virtual ONTAP Select se implementa y está activa en un host de hipervisor, se considera un nodo ONTAP Select.
Clúster de ONTAP Select:: Puede crear un clúster _ONTAP Select_ compuesto por uno, dos, cuatro, seis u ocho nodos. Los clústeres multinodo siempre contienen uno o más pares de alta disponibilidad (HA). Por ejemplo, un clúster de cuatro nodos consta de dos pares de HA. Un clúster de un solo nodo no ofrece capacidad de alta disponibilidad (HA).
Preparación del entorno del host del hipervisor:: Antes de usar la utilidad de administración de implementación para implementar un clúster de ONTAP Select , debe preparar los hosts del hipervisor donde se ejecutará ONTAP Select , incluidos los entornos de almacenamiento y red. Esta preconfiguración del host se realiza fuera del producto ONTAP Select, según los requisitos y limitaciones actuales.
Implementaciones de evaluación versus producción:: Cada nodo de ONTAP Select se ejecuta con una licencia de evaluación o una licencia adquirida. Una licencia de evaluación le permite evaluar ONTAP Select antes de implementarlo en un entorno de producción. La licencia de evaluación se genera y aplica automáticamente. Si implementa un clúster en un entorno de producción, debe adquirir una licencia, lo que implica elegir:
+
--
* Modelo de licencia
* Capacidad de almacenamiento
* Oferta de licencias de plataforma


--
Modelo de licencias por niveles de capacidad:: El modelo de licencias por niveles de capacidad es la opción original para licenciar almacenamiento en una implementación de ONTAP Select . Se basa en el modelo ONTAP utilizado con NetApp AFF y FAS. Se requiere una licencia independiente para cada nodo. La capacidad de almacenamiento está limitada al nodo y es perpetua (no requiere renovación).
Modelo de licencias de pools de capacidad:: El modelo de licencias de grupos de capacidad se introdujo con ONTAP Select 9.5 mediante Deploy 2.10. Se requiere una licencia independiente para cada grupo de capacidad de almacenamiento. La licencia de grupo de capacidad está vinculada a una instancia de License Manager (es decir, una instancia de Deploy) y debe renovarse según las condiciones de compra. Puede licenciar y usar cualquier número de grupos de capacidad en su organización. Sin embargo, dado que los grupos de capacidad son compartidos por los nodos de ONTAP Select , normalmente se requieren menos licencias que con las licencias por niveles de capacidad.
Administrador de licencias:: El Administrador de Licencias es un componente de software compatible con el licenciamiento de Pools de Capacidad. Actualmente forma parte de la utilidad de administración de Deploy. LM alquila almacenamiento a los nodos de ONTAP Select de los pools compartidos que administra. El _ID de Bloqueo de Licencia_ es una cadena numérica que identifica de forma única cada instancia de LM y, por lo tanto, cada instancia de Deploy. Debe usar tanto el número de serie de la licencia de Pool de Capacidad como el LLID para generar un archivo de licencia.
Ofertas de licencias de plataforma:: Hay tres ofertas de licencia disponibles que determinan las capacidades de tamaño de la máquina virtual ONTAP Select cuando compra una licencia:
+
--
* Estándar
* De primera calidad
* Premium XL


--


Para obtener más información, consulte las dos secciones _Plan_ y _Licencia_.

Grupos de almacenamiento versus almacenes de datos:: Un pool de almacenamiento de ONTAP Select es un contenedor de datos lógico diseñado para abstraer y ocultar el almacenamiento físico subyacente. Un pool de almacenamiento es independiente del hipervisor. Al implementarse en un host con hipervisor ESXi, el pool de almacenamiento de ONTAP Select es sinónimo del almacén de datos de VMware.
MTU del clúster:: La MTU del clúster es una función que permite configurar el tamaño de la MTU utilizada en la red interna con un clúster multinodo de ONTAP Select . La utilidad de administración de implementación ajusta el tamaño de la MTU a medida que se configuran los pares de alta disponibilidad (HA) para adaptarse a su entorno de red. También puede configurar el valor manualmente.
VNAS ONTAP Select:: La solución ONTAP Select vNAS permite que un nodo ONTAP Select acceda a almacenes de datos VMware en almacenamiento externo. Con ONTAP Select vNAS, ya no se necesita una controladora RAID local; se asume que la funcionalidad RAID la proporciona el almacenamiento remoto. ONTAP Select vNAS se puede configurar de las siguientes maneras:
+
--
* VMware vSAN
* Matriz de almacenamiento externo genérico


--


En ambos casos, el almacenamiento externo debe configurarse antes de crear un clúster ONTAP Select o expandir la capacidad de almacenamiento de un nodo existente.

Rehospedaje de nodos en la máquina virtual ESXi:: Cuando se implementa un clúster que usa almacenamiento externo disponible a través de la solución ONTAP Select vNAS (ya sea VMware vSAN o una matriz de almacenamiento externo genérica), la máquina virtual ESXi que aloja el nodo ONTAP Select se puede mover a través de acciones que utilizan las siguientes funciones de VMware:
+
--
* vMotion
* Alta disponibilidad (HA)
* Programador de recursos distribuidos (DRS)
+
La utilidad ONTAP Select Deploy detecta el movimiento de la máquina virtual como parte de la ejecución de una operación en el clúster, como por ejemplo:

* clúster en línea
* clúster fuera de línea
* almacenamiento adicional
+
Al mover una máquina virtual, la utilidad de implementación actualiza su base de datos interna y configura el nuevo host ESXi. Todas las acciones realizadas en el nodo ONTAP Select se bloquean hasta que se completen el movimiento de la máquina virtual y las actualizaciones de implementación.



--
Abrir vSwitch para KVM:: Open vSwitch (OVS) es una implementación de software de un conmutador virtual compatible con múltiples protocolos de red. OVS es de código abierto y está disponible bajo la Licencia Apache 2.0.
Servicio de mediación:: La utilidad ONTAP Select Deploy incluye un servicio de mediación que se conecta a los nodos de los clústeres activos de dos nodos. Este servicio supervisa cada par de alta disponibilidad (HA) y ayuda a gestionar fallos.



CAUTION: Si tiene uno o más clústeres de dos nodos activos, la máquina virtual de ONTAP Select Deploy que administra los clústeres debe estar en ejecución permanente. Si la máquina virtual de Deploy se detiene, el servicio de mediación no estará disponible y se perderá la capacidad de alta disponibilidad (HA) para los clústeres de dos nodos.

SDS de MetroCluster:: MetroCluster SDS es una función que ofrece una opción de configuración adicional al implementar un clúster ONTAP Select de dos nodos. A diferencia de una implementación ROBO típica de dos nodos, los nodos de MetroCluster SDS pueden estar separados por una distancia mucho mayor. Esta separación física permite casos de uso adicionales, como la recuperación ante desastres. Se requiere una licencia premium o superior para usar MetroCluster SDS. Además, la red entre los nodos debe cumplir con un requisito mínimo de latencia.
almacén de credenciales:: El almacén de credenciales de implementación es una base de datos segura que almacena las credenciales de las cuentas. Se utiliza principalmente para registrar hosts de hipervisor durante la creación de un nuevo clúster. Consulte la sección "Plan" para obtener más información.
Eficiencia de almacenamiento:: ONTAP Select ofrece opciones de eficiencia de almacenamiento similares a las de las matrices FAS y AFF . Conceptualmente, ONTAP Select con SSD de almacenamiento de conexión directa (DAS) (con una licencia premium) es similar a una matriz AFF . Las configuraciones que utilizan DAS con discos duros y todas las configuraciones de vNAS deben considerarse similares a una matriz FAS . La principal diferencia entre ambas configuraciones es que ONTAP Select con SSD DAS admite la deduplicación de nivel agregado en línea y la deduplicación de nivel agregado en segundo plano. Las demás opciones de eficiencia de almacenamiento están disponibles para ambas configuraciones.
+
--
Las configuraciones predeterminadas de vNAS habilitan una función de optimización de escritura conocida como registro de datos de instancia única (SIDL). Con ONTAP Select 9.6 y versiones posteriores, las funciones de eficiencia de almacenamiento de ONTAP en segundo plano se habilitan con SIDL habilitado. Consulte la sección "Análisis detallado" para obtener más información.

--
Actualización del clúster:: Después de crear un clúster, puede modificar la configuración del clúster o de la máquina virtual fuera de la utilidad de implementación mediante ONTAP o las herramientas de administración del hipervisor. También puede migrar una máquina virtual que genere cambios de configuración. Cuando se producen estos cambios, la utilidad de implementación no se actualiza automáticamente y puede desincronizarse con el estado del clúster. Puede usar la función de actualización del clúster para actualizar la base de datos de configuración de implementación. La actualización del clúster está disponible a través de la interfaz web de usuario de Deploy, el shell de administración de la CLI y la API REST.
RAID de software:: Al utilizar almacenamiento de conexión directa (DAS), la funcionalidad RAID se proporciona tradicionalmente mediante una controladora RAID de hardware local. En su lugar, puede configurar un nodo para que utilice _RAID de software_, donde el nodo ONTAP Select proporciona la funcionalidad RAID. Si utiliza RAID de software, ya no se necesita una controladora RAID de hardware.


[[ontap-select-image-install]]
Instalación de imagen de ONTAP Select:: La utilidad de administración Deploy contiene únicamente una versión de ONTAP Select. Esta versión es la más reciente disponible en el momento del lanzamiento. La función de instalación de imágenes de ONTAP Select permite agregar versiones anteriores de ONTAP Select a la instancia de la utilidad de Deploy, que luego se pueden usar al implementar un clúster de ONTAP Select . Verlink:task_cli_deploy_image_add.html["Agregue imágenes de ONTAP Select para obtener más información"] .



NOTE: Solo debe agregar una imagen de ONTAP Select con una versión anterior a la original incluida en su instancia de Deploy. No se permite agregar versiones posteriores de ONTAP Select sin actualizar también Deploy.

Administración de un clúster de ONTAP Select después de su implementación:: Tras implementar un clúster de ONTAP Select , puede configurarlo como si fuera un clúster de ONTAP basado en hardware. ONTAP Select ejemplo, puede configurarlo mediante el Administrador del sistema o la interfaz de línea de comandos estándar de ONTAP .


.Información relacionada
link:task_cli_deploy_image_add.html["Agregar una imagen de ONTAP Select para implementar"]
