---
sidebar: sidebar 
permalink: concept_api_how_access.html 
keywords: rest api, deploy rest api, rest, access, accessing, how to access 
summary: Debido a la flexibilidad inherente de los servicios web REST, se puede acceder a la API de implementación de ONTAP Select de varias maneras diferentes. 
---
= Cómo acceder a la API de implementación de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debido a la flexibilidad inherente de los servicios web REST, se puede acceder a la API de implementación de ONTAP Select de varias maneras diferentes.


NOTE: La API REST incluida con ONTAP Select Deploy tiene asignado un número de versión. Este número es independiente del número de versión de Deploy. La utilidad de administración ONTAP Select 9.17.1 Deploy incluye la versión 3 de la API REST.



== Implementar la interfaz de usuario nativa de la utilidad

La principal forma de acceder a la API es a través de la interfaz web de ONTAP Select Deploy. El navegador realiza llamadas a la API y reformatea los datos según el diseño de la interfaz. También se accede a la API a través de la interfaz de línea de comandos de la utilidad Deploy.



== Página de documentación en línea de ONTAP Select Deploy

La página de documentación en línea de ONTAP Select Deploy ofrece un punto de acceso alternativo al usar un navegador. Además de permitir la ejecución directa de llamadas a la API individuales, la página también incluye una descripción detallada de la API, incluyendo parámetros de entrada y otras opciones para cada llamada. Las llamadas a la API se organizan en varias áreas o categorías funcionales.



== Programa personalizado

Puede acceder a la API de implementación mediante diversos lenguajes de programación y herramientas. Las opciones más populares incluyen Python, Java y cURL. Un programa, script o herramienta que utiliza la API actúa como un cliente de servicios web REST. Usar un lenguaje de programación le permite comprender mejor la API y le brinda la oportunidad de automatizar las implementaciones de ONTAP Select .
