---
sidebar: sidebar 
permalink: reference_plan_ots_general.html 
keywords: plan, planning, general requirements 
summary: Hay varios requisitos generales que debe tener en cuenta como parte de la planificación de una implementación de ONTAP Select . 
---
= Requisitos de ONTAP Select y consideraciones de planificación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay varios requisitos generales que debe tener en cuenta como parte de la planificación de una implementación de ONTAP Select .



== Conocimientos y habilidades de Linux necesarios para KVM

Linux con el hipervisor KVM es un entorno complejo en el que trabajar. Antes de implementar ONTAP Select en KVM, debe tener los conocimientos y las habilidades necesarias.

Distribución de servidor Linux:: Debe tener experiencia con la distribución de Linux específica que se utilizará para su implementación de ONTAP Select . En concreto, debe ser capaz de realizar las siguientes tareas:
+
--
* Instalar la distribución de Linux
* Configurar el sistema mediante la CLI
* Agregue paquetes de software así como cualquier dependencia


--


Para obtener más información sobre la preparación de su servidor Linux, incluyendo la configuración y los paquetes de software necesarios, consulte la lista de verificación de configuración del host. Consulte los requisitos del hipervisor para las distribuciones de Linux compatibles actualmente.

Implementación y administración de KVM:: Debe estar familiarizado con los conceptos generales de virtualización. Además, existen varios comandos CLI de Linux que debe usar al instalar y administrar ONTAP Select en un entorno KVM:
+
--
* `virt-install`
* `virsh`
* `lsblk`
* `lvs`
* `vgs`
* `pvs`


--
Configuración de redes y Open vSwitch:: Debe estar familiarizado con los conceptos de red y la configuración de conmutadores de red. Además, debe tener experiencia con Open vSwitch. Debe usar los siguientes comandos de red como parte de la configuración de la red ONTAP Select en un entorno KVM:
+
--
* `ovs-vsctl`
* `ip`
* `ip link`
* `systemctl`


--




== Tamaño del clúster y consideraciones relacionadas

Hay varias cuestiones de planificación relacionadas con el tamaño del clúster que debes tener en cuenta.

Número de nodos en el clúster:: Un clúster de ONTAP Select se compone de uno, dos, cuatro, seis u ocho nodos. Debe determinar el tamaño del clúster según los requisitos de la aplicación. Por ejemplo, si se necesita capacidad de alta disponibilidad (HA) para una implementación empresarial, se debe utilizar un clúster multinodo.
Dedicado versus coubicado:: Según el tipo de aplicación, debe determinar si la implementación sigue el modelo dedicado o el de ubicación conjunta. Tenga en cuenta que el modelo de ubicación conjunta puede ser más complejo debido a la diversidad de cargas de trabajo y una mayor integración.




== Consideraciones sobre el host del hipervisor

Hay varias cuestiones de planificación relacionadas con el host del hipervisor que debes tener en cuenta.


CAUTION: No debe modificar directamente la configuración de una máquina virtual de ONTAP Select a menos que el soporte de NetApp se lo indique. Una máquina virtual solo debe configurarse y modificarse mediante la utilidad de administración de implementación. Realizar cambios en una máquina virtual de ONTAP Select fuera de la utilidad de implementación sin la asistencia del soporte de NetApp puede provocar que la máquina virtual falle y quede inutilizable.

Independiente del hipervisor:: Tanto ONTAP Select como la utilidad de administración de ONTAP Select Deploy son independientes del hipervisor. Ambos son compatibles con los siguientes hipervisores.
+
--
* VMware ESXi
* Máquina virtual basada en kernel (KVM)


--



NOTE: A partir de ONTAP Select 9.14.1, se ha restablecido la compatibilidad con el hipervisor KVM. Anteriormente, en ONTAP Select 9.10.1 se eliminó la compatibilidad para implementar un nuevo clúster en un hipervisor KVM, y en ONTAP ONTAP Select 9.11.1 se eliminó la compatibilidad para administrar clústeres y hosts KVM existentes, excepto para desconectarlos o eliminarlos.

Consulte la información de planificación específica del hipervisor y las notas de la versión para obtener detalles adicionales sobre las plataformas compatibles.

Hipervisor para ONTAP Select nodos y utilidad de administración:: Tanto la utilidad de administración Deploy como los nodos de ONTAP Select se ejecutan como máquinas virtuales. El hipervisor que elija para la utilidad Deploy es independiente del que elija para los nodos de ONTAP Select . Tiene total flexibilidad al combinar ambos:
+
--
* La utilidad de implementación que se ejecuta en VMware ESXi puede crear y administrar clústeres ONTAP Select en VMware ESXi o KVM
* La utilidad de implementación que se ejecuta en KVM puede crear y administrar clústeres ONTAP Select en VMware ESXi o KVM


--
Una o más instancias de nodo ONTAP Select por host:: Cada nodo de ONTAP Select se ejecuta como una máquina virtual dedicada. Se pueden crear varios nodos en el mismo host de hipervisor, con las siguientes restricciones:
+
--
* No es posible ejecutar varios nodos de un mismo clúster de ONTAP Select en el mismo host. Todos los nodos de un host específico deben pertenecer a diferentes clústeres de ONTAP Select .
* Debes utilizar almacenamiento externo.
* Si usa RAID de software, solo podrá implementar un nodo ONTAP Select en el host.


--
Consistencia del hipervisor para los nodos dentro de un clúster:: Todos los hosts dentro de un clúster ONTAP Select deben ejecutarse en la misma versión y lanzamiento del software de hipervisor.
Número de puertos físicos en cada host:: Debe configurar cada host para que use uno, dos o cuatro puertos físicos. Si bien tiene flexibilidad para configurar los puertos de red, debe seguir estas recomendaciones siempre que sea posible:
+
--
* Un host en un clúster de un solo nodo debe tener dos puertos físicos.
* Cada host en un clúster de varios nodos debe tener cuatro puertos físicos


--
Integración de ONTAP Select con un clúster basado en hardware de ONTAP:: No es posible agregar un nodo ONTAP Select directamente a un clúster de hardware de ONTAP . Sin embargo, se puede establecer una relación de emparejamiento entre un clúster de ONTAP Select y un clúster de hardware de ONTAP .




== Consideraciones sobre el almacenamiento

Hay varias cuestiones de planificación relacionadas con el almacenamiento del host que debes tener en cuenta.

Tipo de RAID:: Al usar almacenamiento de conexión directa (DAS) en ESXi, debe decidir si usará un controlador RAID de hardware local o la función RAID de software incluida con ONTAP Select. Si utiliza RAID por software, consultelink:reference_plan_ots_storage.html["Consideraciones sobre almacenamiento y RAID"] Para obtener más información.
Almacenamiento local:: Al utilizar almacenamiento local administrado por un controlador RAID, debe decidir lo siguiente:
+
--
* Si utilizar uno o más grupos RAID
* Si utilizar uno o más LUN


--
Almacenamiento externo:: Al utilizar la solución ONTAP Select vNAS, debe decidir dónde se ubican los almacenes de datos remotos y cómo acceder a ellos. ONTAP Select vNAS admite las siguientes configuraciones:
+
--
* VMware vSAN
* Matriz de almacenamiento externo genérico


--
Estimación del almacenamiento necesario:: Debe determinar la cantidad de almacenamiento necesaria para los nodos de ONTAP Select . Esta información es necesaria para adquirir las licencias con capacidad de almacenamiento. Consulte Restricciones de capacidad de almacenamiento para obtener más información.



NOTE: La capacidad de almacenamiento de ONTAP Select corresponde al tamaño total permitido de los discos de datos conectados a la máquina virtual ONTAP Select .

Modelo de licencias para la implementación en producción:: Debe seleccionar el modelo de licencias "Niveles de Capacidad" o "Grupos de Capacidad" para cada clúster de ONTAP Select implementado en un entorno de producción. Consulte la sección "Licencia" para obtener más información.




== Autenticación mediante el almacén de credenciales

El almacén de credenciales de ONTAP Select Deploy es una base de datos que contiene información de la cuenta. Deploy utiliza las credenciales de la cuenta para realizar la autenticación del host como parte de la creación y administración del clúster. Debe tener en cuenta cómo se utiliza el almacén de credenciales al planificar una implementación de ONTAP Select .


NOTE: La información de la cuenta se almacena de forma segura en la base de datos utilizando el algoritmo de cifrado Estándar de cifrado avanzado (AES) y el algoritmo hash SHA-256.

Tipos de credenciales:: Se admiten los siguientes tipos de credenciales:
+
--
* anfitrión
+
La credencial *host* se utiliza para autenticar un host de hipervisor como parte de la implementación de un nodo ONTAP Select directamente en ESXi o KVM.

* vCenter
+
La credencial *vcenter* se utiliza para autenticar un servidor vCenter como parte de la implementación de un nodo ONTAP Select en ESXi cuando el host es administrado por VMware vCenter.



--
Acceso:: Se accede al almacén de credenciales internamente durante las tareas administrativas habituales con Deploy, como agregar un host de hipervisor. También puede administrar el almacén de credenciales directamente a través de la interfaz web y la CLI de Deploy.


.Información relacionada
* link:reference_plan_ots_storage.html["Consideraciones sobre almacenamiento y RAID"]

