---
sidebar: sidebar 
permalink: reference_plan_dep_general.html 
keywords: plan, planning, ontap select deploy, general requirements 
summary: Hay varios requisitos generales que debe tener en cuenta como parte de la planificación para instalar la utilidad de administración ONTAP Select Deploy. 
---
= Requisitos generales y planificación de ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay varios requisitos generales que debe tener en cuenta como parte de la planificación para instalar la utilidad de administración ONTAP Select Deploy.



== Emparejamiento de la utilidad de implementación con los clústeres ONTAP Select

Tiene varias opciones al emparejar una instancia de la utilidad Implementar con los clústeres ONTAP Select .


NOTE: En todos los escenarios de implementación, un solo clúster de ONTAP Select y sus nodos solo pueden administrarse con una instancia de la utilidad de administración Deploy. Un clúster no puede administrarse con dos o más instancias diferentes de la utilidad Deploy.

.Una instancia de la utilidad para cada clúster de ONTAP Select
Puede implementar y administrar cada clúster de ONTAP Select mediante una instancia dedicada de la utilidad de implementación. Con esta configuración individual, existe una clara separación entre cada par de utilidades y clúster. Esta configuración proporciona un alto nivel de aislamiento con dominios de fallo más pequeños.

.Una instancia de la utilidad para múltiples clústeres de ONTAP Select
Puede implementar y administrar varios clústeres de ONTAP Select en su organización con una sola instancia de la utilidad de implementación. Con esta configuración de uno a muchos, todos los datos de procesamiento y configuración se administran con la misma instancia de la utilidad de implementación.


NOTE: Una instancia de la utilidad Deploy puede administrar hasta 400 nodos ONTAP Select o 100 clústeres.



== Requisitos relacionados con el entorno KVM

Antes de instalar la utilidad de administración Deploy en un entorno de hipervisor KVM, debe revisar los requisitos básicos y prepararse para la implementación.

.Requisitos y restricciones para una implementación
Hay varios requisitos y restricciones que debe tener en cuenta al instalar la utilidad ONTAP Select Deploy en un entorno KVM.

.Requisitos de hardware del servidor host KVM de Linux
Su host de hipervisor KVM de Linux debe cumplir varios requisitos mínimos de recursos. Verifique que los hosts donde se implementa ONTAP Select cumplan con los siguientes requisitos básicos:

* Servidor Linux:
+
** El hardware y el software deben ser de 64 bits.
** El servidor debe cumplir con las mismas versiones compatibles definidas para un nodo ONTAP Select


* CPU virtuales (2)
* Memoria virtual (4 GB)
* Almacenamiento (40 GB)
* "El Protocolo de configuración dinámica de host (DHCP) está habilitado (también puede asignar una dirección IP estática)


.Conectividad de red
Verifique que la interfaz de red de la máquina virtual Deploy esté configurada y pueda conectarse a los hosts ONTAP Select que administra.

.Compatibilidad con la versión 4 de IP
ONTAP Select Deploy solo es compatible con la versión 4 de IP (IPv4). No es compatible con la versión 6 de IP (IPv6). Esta restricción afecta a ONTAP Select de las siguientes maneras:

* Debe asignar una dirección IPv4 al LIF de administración de la VM de implementación.
* La implementación no puede crear nodos ONTAP Select configurados para usar IPv6 en los LIF de ONTAP .




== Información de configuración requerida

Como parte de la planificación de su implementación, debe determinar la información de configuración requerida antes de instalar la utilidad de administración ONTAP Select Deploy.

.Nombre de la máquina virtual de implementación
El nombre que se utilizará para la máquina virtual.

.Nombre del host KVM de Linux
El host KVM de Linux donde está instalada la utilidad de implementación.

.Nombre del grupo de almacenamiento
El grupo de almacenamiento que contiene los archivos de la máquina virtual (se requieren aproximadamente 40 GB).

.Red para la máquina virtual
La red donde está conectada la VM de implementación.



== Información de configuración de red opcional

La máquina virtual de implementación se configura mediante DHCP de forma predeterminada. Sin embargo, si es necesario, puede configurar manualmente la interfaz de red de la máquina virtual.

.Host name
El nombre del host.

.Dirección IP del host
La dirección IPv4 estática.

.Máscara de subred
La máscara de subred, que se basa en la red de la que forma parte la máquina virtual.

.Puerta
La puerta de enlace o enrutador predeterminado.

.Servidor DNS primario
El servidor de nombres de dominio principal.

.Servidor DNS secundario
El servidor de nombres de dominio secundario.

.Dominios de búsqueda
Los dominios de búsqueda a utilizar.



== Autenticación mediante el almacén de credenciales

El almacén de credenciales de ONTAP Select Deploy es una base de datos que contiene información de la cuenta. Deploy utiliza las credenciales de la cuenta para realizar la autenticación del host como parte de la creación y administración del clúster. Debe tener en cuenta cómo se utiliza el almacén de credenciales al planificar una implementación de ONTAP Select .


NOTE: La información de la cuenta se almacena de forma segura en la base de datos utilizando el algoritmo de cifrado AES y el algoritmo hash SHA-256.

.Tipos de credenciales
Se admiten los siguientes tipos de credenciales:

* Host Se utiliza para autenticar un host de hipervisor como parte de la implementación de un nodo ONTAP Select directamente en VMware ESXi
* vCenter Se utiliza para autenticar un servidor vCenter como parte de la implementación de un nodo ONTAP Select en ESXi cuando el host es administrado por VMware vCenter


.Acceso
Se accede al almacén de credenciales internamente durante las tareas administrativas habituales con Deploy, como agregar un host de hipervisor. También puede administrar el almacén de credenciales directamente a través de la interfaz web y la CLI de Deploy.
