---
sidebar: sidebar 
permalink: reference_plan_dep_vmware.html 
keywords: plan, planning, ontap select deploy, vmware requirements 
summary: Hay varios requisitos y restricciones específicos del entorno VMware que debe tener en cuenta antes de instalar la utilidad ONTAP Select Deploy en un entorno VMware. 
---
= Consideraciones sobre el host del hipervisor de ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay varias cuestiones de planificación relacionadas con el host del hipervisor que debes tener en cuenta.


CAUTION: No debe modificar directamente la configuración de una máquina virtual de ONTAP Select a menos que el soporte de NetApp se lo indique. Una máquina virtual solo debe configurarse y modificarse mediante la utilidad de administración de implementación. Realizar cambios en una máquina virtual de ONTAP Select fuera de la utilidad de implementación sin la asistencia del soporte de NetApp puede provocar que la máquina virtual falle y quede inutilizable.



== Independiente del hipervisor

Tanto ONTAP Select como la utilidad de administración ONTAP Select Deploy son independientes del hipervisor.

Los siguientes hipervisores son compatibles con la administración de ONTAP Select y ONTAP Select Deploy:

* VMware ESXi
* Máquina virtual basada en kernel (KVM)



NOTE: Consulte la información de planificación específica del hipervisor y las notas de la versión para obtener detalles adicionales sobre las plataformas compatibles.

.Hipervisor para ONTAP Select nodos y utilidad de administración
Tanto la utilidad de administración Deploy como los nodos de ONTAP Select se ejecutan como máquinas virtuales. El hipervisor que elija para la utilidad Deploy es independiente del que elija para los nodos de ONTAP Select . Tiene total flexibilidad al combinar ambos:

* La utilidad de implementación que se ejecuta en VMware ESXi puede crear y administrar clústeres ONTAP Select en VMware ESXi o KVM
* La utilidad de implementación que se ejecuta en KVM puede crear y administrar clústeres ONTAP Select en VMware ESXi o KVM


.Una o más instancias de nodo ONTAP Select por host
Cada nodo de ONTAP Select se ejecuta como una máquina virtual dedicada. Se pueden crear varios nodos en el mismo host de hipervisor, con las siguientes restricciones:

* No es posible ejecutar varios nodos de un mismo clúster de ONTAP Select en el mismo host. Todos los nodos de un host específico deben pertenecer a diferentes clústeres de ONTAP Select .
* Debes utilizar almacenamiento externo.
* Si usa RAID de software, solo podrá implementar un nodo ONTAP Select en el host.


.Consistencia del hipervisor para los nodos dentro de un clúster
Todos los hosts dentro de un clúster ONTAP Select deben ejecutarse en la misma versión y lanzamiento del software de hipervisor.

.Número de puertos físicos en cada host
Debe configurar cada host para que use uno, dos o cuatro puertos físicos. Si bien tiene flexibilidad para configurar los puertos de red, debe seguir estas recomendaciones siempre que sea posible:

* Un host en un clúster de un solo nodo debe tener dos puertos físicos.
* Cada host en un clúster de varios nodos debe tener cuatro puertos físicos


.Integre ONTAP Select con un clúster basado en hardware de ONTAP
No es posible agregar un nodo ONTAP Select directamente a un clúster de hardware de ONTAP . Sin embargo, se puede establecer una relación de emparejamiento entre un clúster de ONTAP Select y un clúster de hardware de ONTAP .



== Entorno de hipervisor de VMware

Hay varios requisitos y restricciones específicos del entorno VMware que debe tener en cuenta antes de instalar la utilidad ONTAP Select Deploy en un entorno VMware.

.Requisitos de hardware del servidor host ESXi
Su host de hipervisor ESXi debe cumplir varios requisitos mínimos de recursos. Asegúrese de que los hosts donde se implementa ONTAP Select cumplan con los siguientes requisitos básicos:

* Servidor ESXi:
+
** El hardware y el software deben ser de 64 bits
** Debe adherirse a las mismas versiones compatibles definidas para un nodo ONTAP Select


* CPU virtuales (2)
* Memoria virtual (4 GB)
* Almacenamiento (40 GB)
* DHCP habilitado (también puede asignar una dirección IP estática)


.Conectividad de red
Debe asegurarse de que la interfaz de red de la máquina virtual ONTAP Select Deploy esté configurada y tenga una única dirección IP de administración. Puede usar DHCP para asignar dinámicamente una dirección IP o configurar manualmente una dirección IP estática.

Según sus decisiones de implementación, la máquina virtual de implementación debe poder conectarse al servidor vCenter, a los hosts del hipervisor ESXi y a los nodos de ONTAP Select que administra. Debe configurar sus firewalls para permitir el tráfico requerido.

Deploy utiliza la API de VMware VIX para comunicarse con el servidor vCenter y los hosts ESXi. Inicialmente, establece una conexión mediante SOAP sobre SSL en el puerto TCP 443. Posteriormente, se establece una conexión mediante SSL en el puerto 902. Además, Deploy emite comandos PING para verificar que haya un host ESXi en la dirección IP especificada.

La implementación también debe poder comunicarse con las direcciones IP de administración del clúster y del nodo ONTAP Select mediante los siguientes protocolos:

* Comando PING (ICMP)
* SSH (puerto 22)
* SSL (puerto 443)


.Compatibilidad con la versión 4 de IP
ONTAP Select Deploy solo es compatible con la versión 4 de IP (IPv4). No es compatible con la versión 6 de IP (IPv6). Esta restricción afecta a ONTAP Select de las siguientes maneras:

* Debe asignar una dirección IPv4 al LIF de administración de la máquina virtual de implementación.
* La implementación no puede crear nodos ONTAP Select configurados para usar IPv6 en los LIF de ONTAP .




== Consideraciones sobre la implementación del servidor VMware vCenter en ONTAP Select



=== Privilegios de VMware vSphere para ESA

A continuación, se enumeran los privilegios específicos para la biblioteca de contenido de vSphere que necesita para crear y administrar vSAN Express Storage Architecture (ESA) en vCenter:

* Agregar elemento de biblioteca
* Crear una biblioteca local
* Eliminar elemento de la biblioteca
* Eliminar biblioteca local
* Almacenamiento de lectura
* Actualizar archivos
* Actualizar biblioteca
* Actualizar elemento de la biblioteca
* Actualizar la biblioteca local

