---
sidebar: sidebar 
permalink: task_cli_signing_in.html 
keywords: administer, administering, cli, deploy, sign in, signing in 
summary: Debe iniciar sesión en el shell de administración de Deploy mediante SSH. Después de iniciar sesión, puede ejecutar comandos CLI para crear un clúster de ONTAP Select y realizar los procedimientos administrativos relacionados. 
---
= Sign in en ONTAP Select Deploy usando SSH
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debe iniciar sesión en el shell de administración de Deploy mediante SSH. Después de iniciar sesión, puede ejecutar comandos CLI para crear un clúster de ONTAP Select y realizar los procedimientos administrativos relacionados.

.Antes de empezar
Debe tener la contraseña actual de la cuenta de administrador de Deploy (admin). Si inicia sesión por primera vez y utilizó vCenter para instalar la máquina virtual de Deploy, debe usar la contraseña establecida durante la instalación.

.Pasos
. Sign in utilizando la cuenta de administrador y la dirección IP de administración de la máquina virtual de implementación; por ejemplo:
+
`ssh admin@<10.235.82.22>`

. Si es la primera vez que inicia sesión y no instaló Deploy mediante el asistente disponible con vCenter, proporcione la siguiente información de configuración cuando se le solicite:
+
** Nueva contraseña para la cuenta de administrador (obligatoria)
** Nombre de la empresa (obligatorio)
** URL de proxy (opcional)


. Escriba *?* y presione *Enter* para mostrar una lista de los comandos de shell de administración disponibles.

