---
sidebar: sidebar 
permalink: task_lic_acquire_ct.html 
keywords: license, licensing, acquire, Capacity Tiers 
summary: Al utilizar licencias por niveles de capacidad, debe adquirir un archivo de licencia para cada nodo de ONTAP Select . Este archivo define la capacidad de almacenamiento del nodo y está vinculado a él mediante un número de serie único de nueve dígitos asignado por NetApp. 
---
= Adquirir una licencia de nivel de capacidad ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Al utilizar licencias por niveles de capacidad, debe adquirir un archivo de licencia para cada nodo de ONTAP Select . Este archivo define la capacidad de almacenamiento del nodo y está vinculado a él mediante un número de serie único de nueve dígitos asignado por NetApp.

.Antes de empezar
Debe tener el número de serie de licencia de nueve dígitos asignado al nodo por NetApp. Antes de intentar adquirir un archivo de licencia, debe esperar al menos veinticuatro horas a partir de la fecha de envío de su pedido de compra.

.Acerca de esta tarea
Debe realizar esta tarea para cada nodo de ONTAP Select que requiera una licencia de nivel de capacidad.

.Pasos
. Acceda al sitio de licencias de ONTAP Select mediante un navegador web:
+
`https://register.netapp.com/register/getlicensefile`

. Sign in con las credenciales de su cuenta de NetApp .
. En la página *Generador de licencias*, seleccione la oferta de licencia deseada en el cuadro desplegable.
. Complete los campos restantes en la misma página, incluido el *Número de serie del producto*, que es el número de serie del nodo ONTAP Select .
. Haga clic en *Enviar*.
. Una vez validada la solicitud, seleccione el método de entrega de la licencia.
+
Puede hacer clic en *Descargar licencia* o *Enviar licencia por correo electrónico*.

. Confirme que recibió el archivo de licencia según el método de entrega seleccionado.


.Después de terminar
Debe cargar el archivo de licencia en la utilidad de administración de Implementación antes de que pueda aplicarse a un nodo ONTAP Select .
