---
sidebar: sidebar 
permalink: task_adm_connectivity.html 
keywords: administer, administering, web, connectivity, network connectivity, network checker 
summary: Puede probar la conectividad de red entre dos o más nodos de ONTAP Select en la red interna del clúster. Normalmente, esta prueba se ejecuta antes de implementar un clúster multinodo para detectar problemas que podrían provocar un fallo en la operación. 
---
= Confirmar la conectividad entre los nodos de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede probar la conectividad de red entre dos o más nodos de ONTAP Select en la red interna del clúster. Normalmente, esta prueba se ejecuta antes de implementar un clúster multinodo para detectar problemas que podrían provocar un fallo en la operación.

.Antes de empezar
Todos los nodos ONTAP Select incluidos en la prueba deben estar configurados y encendidos.

.Acerca de esta tarea
Cada vez que se inicia una prueba, se crea una nueva ejecución de proceso en segundo plano y se le asigna un identificador de ejecución único. Solo puede haber una ejecución activa a la vez.

La prueba tiene dos modos que controlan su funcionamiento:

* Rápido: Este modo realiza una prueba básica sin interrupciones. Se realiza una prueba de ping, junto con una prueba del tamaño de la MTU de la red y del vSwitch.
* Extendido: Este modo realiza una prueba más exhaustiva en todas las rutas de red redundantes. Si se ejecuta en un clúster de ONTAP Select activo, el rendimiento del clúster puede verse afectado.



NOTE: Se recomienda realizar siempre una prueba rápida antes de crear un clúster multinodo. Una vez realizada correctamente, puede realizar una prueba extendida según sus requisitos de producción.

.Pasos
. Sign in en la interfaz de usuario web de la utilidad de implementación utilizando la cuenta de administrador.
. Haga clic en la pestaña *Administración* en la parte superior de la página y haga clic en *Comprobador de red*.
. Haga clic en *Iniciar nueva ejecución* y seleccione los hosts y las redes para el par HA
+
Puede agregar y configurar pares HA adicionales según sea necesario.

. Haga clic en *Iniciar* para comenzar la prueba de conectividad de red.

