---
sidebar: sidebar 
permalink: task_adm_resize.html 
keywords: administer, administering, web, resizing nodes, resizing 
summary: Después de implementar un clúster ONTAP Select , puede actualizar el tipo de instancia de hipervisor de los nodos mediante la utilidad de administración Implementar. 
---
= Cambiar el tamaño de los nodos del clúster ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Después de implementar un clúster ONTAP Select , puede actualizar el tipo de instancia de hipervisor de los nodos mediante la utilidad de administración Implementar.


NOTE: Puede realizar la operación de cambio de tamaño de los nodos del clúster cuando utilice el modelo de licencia de Niveles de capacidad y el modelo de licencia de Grupos de capacidad.


NOTE: El cambio de tamaño al tipo de instancia grande solo se admite en ESXi.

.Antes de empezar
El clúster debe estar en estado en línea.

.Acerca de esta tarea
Esta tarea describe cómo usar la interfaz web de Deploy. También puede usar la CLI de Deploy para redimensionar la instancia. Independientemente de la interfaz que utilice, el tiempo necesario para la operación de redimensionamiento puede variar significativamente en función de varios factores y puede tardar bastante tiempo en completarse. Solo puede redimensionar un nodo a un tamaño mayor.

.Pasos
. Sign in en la interfaz de usuario web de la utilidad de implementación utilizando la cuenta de administrador.
. Haga clic en la pestaña *Clúster* en la parte superior de la página y seleccione el clúster deseado de la lista.
. En la página de detalles del clúster, haga clic en el ícono de engranaje a la derecha de la página y seleccione *Cambiar tamaño de instancia*.
. Seleccione el *Tipo de instancia* y proporcione las credenciales de ONTAP , luego haga clic en *Modificar*.


.Después de terminar
Debes esperar a que se complete la operación de cambio de tamaño.
