---
sidebar: sidebar 
permalink: task_cli_deploy_image_remove.html 
keywords: administer, administering, cli, deploy, ontap select image, remove 
summary: Puede eliminar imágenes de ONTAP Select de su instancia de la utilidad de administración Deploy cuando ya no sean necesarias. 
---
= Eliminar una imagen de ONTAP Select de la implementación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede eliminar imágenes de ONTAP Select de su instancia de la utilidad de administración Deploy cuando ya no sean necesarias.


CAUTION: No debe eliminar ninguna imagen de ONTAP Select que esté siendo utilizada por un clúster.

.Acerca de esta tarea
Puede eliminar imágenes de ONTAP Select más antiguas que actualmente no estén en uso en un clúster o que no estén planificadas para usarse con una implementación de clúster futura.

.Pasos
. Sign in en la CLI de la utilidad de implementación usando SSH con la cuenta de administrador (admin).
. Muestra los clústeres administrados por Deploy y registra las imágenes de ONTAP en uso:
+
[source, cli]
----
cluster show
----
+
Tenga en cuenta el número de versión y la plataforma del hipervisor en cada caso.

. Inicie el shell Bash:
+
[source, cli]
----
shell bash
----
. Mostrar todas las imágenes disponibles de ONTAP Select :
+
[source, cli]
----
ls -lh /opt/netapp/images
----
. Opcionalmente, elimine la imagen ONTAP Select con su host de hipervisor.
+
[role="tabbed-block"]
====
.Ejemplo de ESXi
--
[source, asciidoc]
----
rm -r /opt/netapp/images/DataONTAPv-9.3RC1-vidconsole-esx.ova
----
--
.Ejemplo de KVM
--
[source, asciidoc]
----
rm -r /opt/netapp/images/DataONTAPv-9.3RC1-serialconsole-kvm.raw.tar
----
--
====

