---
sidebar: sidebar 
permalink: task_adm_mediators.html 
keywords: administer, administering, web, mediators 
summary: Cada clúster de dos nodos de ONTAP Select es monitoreado por el servicio mediador, que ayuda a administrar la capacidad de alta disponibilidad compartida por los nodos. 
---
= Administrar los servicios de mediación de ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cada clúster de dos nodos de ONTAP Select es monitoreado por el servicio mediador, que ayuda a administrar la capacidad de alta disponibilidad compartida por los nodos.



== Ver el estado del servicio de mediación

Puede ver el estado del servicio mediador con respecto a cada uno de los clústeres de dos nodos definidos en la utilidad ONTAP Select Deploy.

.Acerca de esta tarea
Puede ver la configuración de cada mediador, incluyendo su estado actual, los dos nodos ONTAP Select y el destino iSCSI donde se almacena la información de control de alta disponibilidad (HA). Pase el cursor sobre los objetos de la página para ver información detallada.

.Pasos
. Sign in en la interfaz de usuario web de la utilidad de implementación utilizando la cuenta de administrador.
. Haga clic en la pestaña *Administración* en la parte superior de la página y haga clic en *Mediadores*.
. Opcionalmente, haga clic en *Filtro* para personalizar su vista de los clústeres de dos nodos monitoreados por el servicio mediador.

